import { format } from 'prettier'

export { default as Home } from './Home'
export { default as Bill } from './Bill'
export { default as BillForm } from './BillForm'
export { default as Customer } from './Customer'
export { default as Medicine } from './Medicine'
export { default as Vendor } from './Vendor'
export { default as Stock } from './Stock'
export { default as Expense } from './Expense'
export { default as Purchase } from './Purchase'
export { default as PurchaseForm } from './PurchaseForm'
export { default as Report } from './Report'
export { default as Admin } from './Admin'
export { default as Login } from './Login'
export { default as Registration } from './Registration'
export { default as Manufacturer } from './Manufacturer'
export { default as Grn } from './Grn'
export { default as GrnForm } from './GrnForm'
export { default as Setting } from './Setting'

export { default as LandingPage } from './LandingPage'
export { default as SuperAdmin } from './SuperAdmin.jsx'
